name: Discloud Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual running

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Required to use the file system
      - uses: discloud/deploy-action@v1
        with:
          token: ${{ secrets.DISCLOUD_TOKEN }} # Required
          app_id: "azurajs"
